### ISSUE TITLE
UX: if user clicks on birb to navigate to today, they cannot see the popup

### ISSUE THREAD

**Issue by lyqht** [GoogleChromeLabs/designcember#21]
Here's a GIF for what I meant

![cannot see pop up if use birb](https://user-images.githubusercontent.com/35736525/144696387-e0469e49-6c4f-42e2-8f39-8f5dd0076cb1.gif)

If the user clicks on the birb to navigate to today, 
- they will brought to the number container, and not at the centre of the window container. 
- they cannot see the pop up unless they scroll up to the top of the window

**Comment by argyleink** [comment]
regression from tooltips showing "above" when the day is below the viewport. my hunch says the tooltip tries to position itself right away when the birb is clicked (hence it shows above), and then goes out of view (ironic because it was trying to be in view).

solution is likely to defer tooltip placement to after scroll

thanks for reporting!

**Comment by argyleink** [comment]
fix will deploy on the hour, let me know if the problem is gone or you're still finding scenarios where the popup is outside the viewport 👍🏻 

this was a good fix, the timing has been improved thanks to your logged issue 🙂
